
select * from movie_comment


Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (31,'윌스미스는 나이도 안먹나봐 ㅎ 멋있다','윌 스미스 레전드..','너무 크게 기대를 했었나? 좀 지루했다...',null,null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (32,null,null,'연애와 직장, 모든것에 공감하며 미친듯이 웃음','연애 감정은 아슬아슬 플러팅과 알코올을 타고...','영화가 술 처먹다 끝나네요 ㅋㅋㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (44,'귀엽고귀엽고귀엽고첨부터끝까지귀염',null,'환장하는 귀여움과 완벽한 스토리라인!!엔딩까지 너무 매력적인 영화','귀엽다는거 하나 빼면 스토리 개 망작...',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (34,null,'연애는 넷플릭스에서 하는 중이니까 좋게 말할때 빠른 시일내로 2편 내놔라','키싱부스 이름만들어도 심장이 두근거리지','노아는 어장관리 남이고.. 리는 친구랑 여친사이에 구분도 없는 찌질이..',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (39,null,'가볍게 즐길만한 로맨스 였다.','하이틴 로맨스 코미디물 중에서 최고..','자식을 생각하는 아빠 연기를 무척 잘한다. 마음에 와닿더라..',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (45,'속시원한 액션. 성인들을 위한 강렬한 팝콘무비.',null,'재밋음 액션도 멋지고 극장에서봤음 더 쩔었을거같은데 모니터로보기엔 아쉬움ㅋ','이유없이 너무 잔인하고 스토리가 산만하다. 진짜 영상은 트랜스포머 같고 그냥 잔인한 트랜스포머 보는것 같음',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (55,'최고의명작 액션영화 그당시 매트릭스4라고도 광고했는데 매트릭스와 맞먹을 명작 영화',null,'2는 대체 언제 나오냐..기다리다 목 빠지겄다','키아누형 콘스탄틴2 찍어줘요 제발요 너님 어차피 불사신이잖음 찍어줘',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (56,null,null,'DC는 감독하고 작가들 교체해라진짜 중반부터는 내내 한숨만나오더라..','절정에 닿을수록 힘빠지는클리셰 무엇보다 원작 팬들을 무시한 아이덴티티가 사라진 로맨티스트 조커 돈 오브 저스티스보다 쓰레기','할리퀸 진짜 뭐 저렇게 이쁘냐..');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (57,'액션영화좋아하는사람한테 정말 취저에요 ㅜㅜ넷플릭스에서 끝까지 본 몇안되는 영화',null,'너무 재밌어요 액션 지리고 오랜만에 처음부터 끝까지 다른 짓 안하고 끝까지 본 영화네요 이거 2는 언제 나와요ㅠㅠ','샤롤리즈테론 아니였으면 어쩔뻔했음 ㅋㅋㅋㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (178,null,null,'미션임파서블은 시리즈가 지날수록 발전하는듯','이런 영화는 한국에서 못나오나?','톰크루즈는 늙지를 않는구나...');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (98,null,'박새로이와 오수아와의 첫사랑에 관한 서사 참 아름답네요~~~',null,'더할 나위 없이 훌륭한 서사와 연기가 아름다운 영상과 음악과 만나 이루어진 완벽한 이야기~~','박새로이 머리 해주세요~~ 30분후 쪽박ㅠㅠ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (35,'유쾌 통쾌 상쾌 삼박자가 잘 맞아 보는 관객들로 씐나게 들썩이게 한다',null,'황정민,유해진,오달수의 연기력 대박',null,'떡밥은 뿌려놓고 회수를 안하고 유치한 장면과 대사');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (37,null,'달달하고 로멘틱',null,'아~ 1보다도 재밌는 2였다..','그래서 대학은 어디..? 시즌 3 나오는건가??');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (52,'한국영화는 두번이상 본게 없는데 아저씬 몇십번을 봐도 잼난다 ㅋ',null,'스토리든 뭐든 원빈의 눈빛이 모든걸 덮었다...',null,'이런영화가또있으려나...');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (172,null,null,'후속편이 기다려진다~~','종이의 집 보고 나면 다른 강도 범죄물 못 보겠다라는 말이 괜히 있는 게 아니다 !','처음 봤을 때 신선한 충격이다..');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (171,'자본이 들어와서 질 높은 드라마를 볼 수 있다는 점에서는 환영할 만한 일인 것 같다.','서양의 좀비에 익숙해져 있는 나에게 짚신과 버선을 신고 한복을 펄럭이며 돌아다니는 좀비를 보게 된다는 점이다.',null,null,'뻔한 좀비 스토리이긴 하지만 뻔한 것을 뻔하지 않게 만들어 내는 영특함이 있는 드라마이다.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (97,null,'사교육에 목을 맨 부모들... 이러지 말자~~','쵝오~! 모든 연기가 좋았다~','사회의 경쟁구도와 입시제도가 끔찍하네요...ㅠㅠ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (66,'이 배우들 데려다가 무슨짓을 한건지~~ㅋ',null,'오랫동안 미드 1위를 차지한데에는 이유가 있네~~','내 취향은 아니다~~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (65,null,null,'다음 후속편도 나오려나~~?','책이나 게임을 접하지 못한 시청자들에겐 난해하고 맥락 없는 작품처럼 느껴진다....','앞으로 보여줄 위쳐의 세계를 기대하게 되는거같아요,,.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (60,'슬기로운 의사생활 다시봐도 재밌어요ㅋㅋ','슬기로운 의사생활도 재밌지만 응팔만큼 찡하진 않은거 같아요. 제 개췬가봐요 ㅋ',null,null,'슬기로운의사생활과 낭만닥터 김사부요~ 대체적으로 의료드라마가 잼나더라구요^^;');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (79,null,'평점은 거짓말을 하지않는다 눈물 펑펑 흘리면서 봤네요ㅜㅜ','못본사람은있어도 한번본사람은 없을영화..;','장마철만 되면 생각나',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (88,'영화 보다가 가방 집어 던질뻔했다..',null,'이런 영화 이제 그만 만들자ㅜㅜ','웃음이 아닌 헛웃음만 나오는 졸작..',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (94,'오랜만에본 따뜻한 로맨스영화',null,'쉽게 헤어나오기 어려운 영화..',null,'꿀잼~~ 보고나서 왜 먹먹한지ㅠㅠ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (95,null,'대만영화라서 편견이 있었는데, 완전히 반성한다...',null,'주걸륜이너무대단하다는생각밖에는~','사랑을 조금이라도 해봣던 사람이라면 이영화에 감동이~');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (96,null,'저 능력 나도 갖고싶다~','하루 하루를 어떻케 살아야 되는지 느끼게 해주는 영화 !!','마지막으로 아버지와 함께 보낼때 눈물 펑펑 쏟았다ㅠㅠ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (128,null,'수녀귀신 너무 무서윘어요',null,'수녀복이 이렇게 무서울 수 있다는게 신기함ㅋ','컨저링만큼 잘만든 영화가 없다');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (129,null,'공포영화를 보면서 두려웠던 적은 진짜 처음이다..','무서운걸 넘어 두려웠던 영화..','뭐~ 이정도면 볼만함',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (130,'여주인공 너무 답답함에 암걸리는 영화 ',null,'무서움은 있었지만 결말은 별로였다','재미있다는 분들 다 장산범입니다',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (151,null,'말그대로 미친영화다','기타치는놈 타이밍 오지게 잘맞추네 ㅋㅋ','천국가고 싶으면 은색락카 한통 사서 입에 뿌려라 ㅋㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (152,'스토리, 영상, 센쓰 돋보이는 영화',null,'1편보다 300퍼센트 낫다',null,'뻔하지 않은 비쥬얼 다음이 기대되는 작품');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (153,null,'감독이 바껴서 망한영화중 하나임.',null,'아빠랑 아들이랑 동년배인줄ㅋㅋㅋ','시리즈를 한순간의 말아먹을수 있는 굉장한 파괴력.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (156,null,'유쾌하고 즐거울 따름 B급인척 하는 A급 영화','카메론디아즈의 리즈시절을 볼수 있어서 좋았다 ㅋㅋㅋ','카메론디아즈의 리즈시절을 볼수 있어서 좋았다 ㅋㅋㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (157,null,'수식어가 필요없는 영화.','노래가너무좋음 코라사랑해','휴 그랜트, 드류 베리모어 로맨틱 코메디 끝판왕',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (158,'감동적이네요.. OST 계속 듣는중..',null,'모든 연출과 배우들이 하나로 잘 뭉쳐짐..',null,'앤 해서웨이 진심 연기 잘했다.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (159,null,'개연성없는 역대급 멜로영화.',null,'잘생긴 정해인 스크린으로 크게 봤다고 생각하면 됨','억지로 레트로멜로 흉내만..');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (161,null,'이런 잔잔한 영화 잘 안보는데 안봤으면 후회할뻔','보는내내 소름이 돋았던영화','다섯손가락안에 꼽는 음악영화',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (162,'퀸의 콘서트에 온 것 같은 기분이 들었음 퀸의 팬이라면 추천',null,'살아생전 못가본 퀸 콘서트에 갔다왔습니다.','오프닝 20세기폭스 나올때 기타변주부터 소름',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (163,null,null,'나는 무엇을 위해 저렇게 땀흘릴 수 있을까?','깨져서 나오거나 깨고 나오거나ㅋㅋ','마지막 십분 몰입도가 어마어마했음');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (164,'아련한 추억 속 한 페이지를 들추는 듯 느껴진 영화',null,'이루어지는 사랑만이 아름다운 사랑이 아니라는 걸 느꼈다','음악은 사랑을 부른다',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (165,'작은 락페스티벌에 다녀온 느낌','노래,연기,분위기,감동, 그리고 뉴욕이 좋다 ㅎㅎ',null,null,'마지막 엔딩크레딧까지 다 보게 만든 영화 !');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (166,null,'엄마의 젊은시절을 처음 상상하게 해준 영화','the winner takes it all 불렀을 때, 미친 소름','보는 내내 지루하지 않은영화 ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (167,'바넘 스타일의 경이로움으로 관객들을 현혹시키는 영화~',null,'레미제라블 이후로 휴잭맨의 인생영화',null,'화려하고 즐거운 음악과 볼거리');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (169,null,'고전에 평을 매길 자격이 우리에겐 없지~',null,'도레미도미도미레미파파미레파~ 영원히 내 기억 속에 남을 음표','내 인생 최고의 영화. 명작 중의 명작');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (170,null,'자스민의 speechless 명장면','디즈니가 미쳤음..실사중 최고였음','윌 스미스가 하드캐리하여 의도치 않게 원작을 뛰어넘은 실사영화',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (184,'현빈 유해진 뜻밖의 케미 ㅋㅋㅋ','현빈의 액션은 볼수록 멋있음~',null,null,'윤아 때문에 진짜 많이 웃었다~ㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (186,'기대 안하고 봤는데 배꼽빠지게 웃고 눈물콧물 쏙뺐네~','조정석은 완전 납득이의 귀환ㅋㅋ','울다 웃다 울다 웃다 무한반복',null,null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (41,'진짜 재미없어서 중간에 보다가 나와버림',null,'예전 맨인블랙이 그립다..','세상에..이렇게 재미없을줄은 ㅠㅠ이 유명한 배우들 데려다가 무슨짓을 한건지.',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (51,null,'이게 어떻게 세계대전z가 원작이라는건지??; 책에 나오는 얘기가 하나도안나왔잖아..','좀비가 벽넘어올때 개지린다 팬티갈아입고옴ㅡㅡ;;','A급 좀비영화~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (54,null,'리들리스콧 + 드니 빌뇌브.. 안볼 이유가,,?','SF물 안좋아하시는분 보지마세요. 3시간동안 한숨만 푹푹쉬고 졸고나왔네요. 개취존중바랍니다.','이 영화에 1점 주는 애들 특징: 전편 안 보고 예고편만 보고 무작정 보러간다.',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (58,'여성들에게 큰 힘이 되어주는 영화. 영상미가 아주 아름다웠고 에놀라의 말 하나하나가 위로와 힘이 되었다.','밀리 바비 브라운 연기 너무 귀엽고 잘함ㅋㅋㅋ',null,null,'셜록홈즈는 왜 갖다 붙인건지 ..ㅋㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (63,'세상이 내 뜻대로 되지 않지만, 괜찮아!',null,'코로나때문 집콕해 살쪄 우울하지만 김수현드라마 볼수만있다면..','머든 괜찮아~ 나도 서예지같은 여친있음...ㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (61,null,null,'와... 이렇게 멋진 드라마를 이제야 보다니...','응답하라 1988 다시보기로 여섯번 봤어요~~','응팔같은 드라마 만들어 주세요');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (67,null,'입장차가 분명한 영화. 약혼남의 입장이였던 사람이라면 너무나 화가나는 영화','말로 표현할수 없이 가슴이 뜨거워지네요','아름다운 영화 다시봐도 정말 재밌네요',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (80,'기억이란 사랑보다 더 슬프다는가사와 영화내용이 너무나도 맞아 떨어졌음.',null,'짜증나는 힘겨운 사랑을 남자는 아름답게..아름다운 사랑을했다.','신세계에서 나오는 장청이 골드문 들어가기전 모습같다고 하는말이 정확함',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (83,null,null,'그냥 말이필요없음 이때까지 본 한국멜로중에 제일 울었던거같다','스토리는 뻔하지만 정우성과 손예진 연기가 너무 아름다웠던','예진 누나 너무 예뻐서 만점~~');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (89,'연인끼리보면좋은영화~','어떡하죠너무재미없었어요 진짜..',null,null,'이상한 전개와 이상한 끝맺음...이승기, 문채원 빨로 만든 영화.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (93,null,'정말 평생 잊혀지지 않을 영화.... 여운이 장난 아님,,','정말 최고의 영화.몇 번을 다시봐도 질리지 않는...','팬텀 목소리 너무 좋다 ㅎㅎ ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (173,null,null,'1994화이팅!흥해라!!','쓰레기오빠 왤케 멋있어?? ♥♥♥♥','응답하라 1997보다 개인적으로 더 재미남');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (174,'호불호가 갈리네..개인적으론 괜찮았음',null,'벌은 타 보고 싶긴 하다.','더락의 덩치가 알로하 하니까 귀엽당',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (175,null,'까메오 때문에 진짜 빵터졌음','차 건물 다 때려부수네 ㅋㅋㅋ',null,'미국 빡빡이랑 영국 빡빡ㅋㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (180,'반전, 그리고 마지막까지 긴장하게 만듭니다. 포르쉐 속도감 하이라이트 짱~^^',null,'1편이 명작으로 남을 것이다.','테이큰재밋어요재밋어요짱짱 니암리슨짱짱',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (47,'에바 그린 때문에 10점 준다','상대편 여자사령관 정말 멋집니다. 대박','전편의 레오니다스만한 매력이 없어서 아쉽네~',null,null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (117,null,'공포영화인줄 알았는데 미친영화였다..','재밌냐 이게?솔직히 이게 재밌냐고','호불호 많이 갈릴듯한 소재',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (119,'이야기가 점점 산으로~~',null,'재밋음. 꼭 보셈','위험할땐 살려주세요말고 아빠를 부르길',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (121,null,null,'뭐 이딴 90년대 어설픈 공포 영화를...','결론 사이비, 신천지는 없어져야할 존재다','반대 많은 이유가 신천지 때문!ㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (122,'사람 머리가 생각보다 얼마나 단단한지 깨닫게 해주는 영화ㅋㅋ',null,'손현주가 이 영화에서 연기한다는것 자체로 이 영화는 볼만한 가치가 있다.','폰은 들고 있으면서 절대 112에는 신고하지 않는 멍청한 주인공들ㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (123,'한줄평을 쓰라는거야..?','... 이 느낌',null,null,'내 짜증을 쓰라는거야 ?모르것다,,');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (124,null,null,'몰입도가 정말 좋고 실화라 더욱 감동적이었습니다','실화라는게 너무 끔찍했던 영화','너무 재밌게 시간가는줄 모르고 봄');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (125,'보는내내 심장이 쫄깃','몰입도 굿~여주인공의 고통ㅠㅠ',null,null,'너무 노잼 상어 고증X 긴장감X');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (126,null,'처음 25분 정도 잼있음...','저런 위험한 짓은 아무리 부부라도 하지말자','의외로 볼만하다~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (127,'개명작 다시봐도 꿀잼 ㅎㅎ',null,'속편이 너무 기다려지는데..',null,'재미와 명작');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (133,'영화애니메이션은 어린이를 위한 것이 아니다','영상부터 스토리 ,음악까지 흠잡을 데가 없음',null,null,'아바타 짝퉁애니메이션버젼^^');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (131,null,null,'아시아 감성을 훑으면서도 동서양 아우르는 시놉. 다같이 즐겁게 쿵후 한 방!','쿵푸팬더 3도 빨리 나왔으면..','값으로 환산할 수 없을 만큼 귀엽고 황홀한 캐릭터');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (132,'올해 최고의 에니매이션~~',null,'세상에서 제일 귀여운 캐릭터를 고르라면 난 미니언을 고를거다..','개잼꿀잼짱잼!!!미니언 한마리 몰고가세요~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (134,null,null,'뮤지컬 애니메이션의 명작','매드 맥스의 감독님이 만들었다는게 더 믿기지 않는다..','환경파괴하지 말자! 펭귄들 살 수 있게...');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (135,'아기새들이 마지막에 마이티레드 합창이 좋네요','너무 귀엽고 유쾌하고 신낫음',null,null,'유치하지도 않고 코믹');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (136,null,'펭귄이랑 기린 귀욤;; 똘끼넘치는 스토리','역시 마다가스카~!~!~!','드림웍스의 창의력이과 개그는 최고',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (137,'스핀오프 같지 않게 재미있음... 고양이의 특성을 잘살려서 리얼함',null,'고양이한테 반한건 처음이네ㅋㅋㅋㅋ',null,'유쾌하고 귀엽고 도도하고... 춤, 액션, 음악도 좋고...');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (138,null,'정말 재밌게 봄~~',null,'특유의 유머코드가 너무 좋음','깊은뜻을모름???ㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (139,null,'성우님들의 더빙이란 이런 것!','꿈을 추구하는 달팽이와 친구','달팽이가 뭐라고 마지막까지 긴장하면서 봤네요ㅋㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (140,'볼만하면서 마지막끝날때 좀 슬프네요',null,'귀여운 테오도르 궁댕이랑 앨빈 사이먼의 깨알같은 귀여움 !!','가족과함께보면더 재미있어요',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (141,null,null,'100번봐도 재밌을것같은 애니메이션 ㅠㅠ','일본 최고의 에니메이션.','인생에 최고의 영상매체');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (142,'하울이 너무 좋다,무대가리도 귀엽고 할망구도 귀엽고ㅋ',null,'역시 어른들의 동화...강추!','중독성이강한 영화~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (143,null,'동물CG와 함께 뛰노는 아이들과 어른들 그리고 곰싸움구경','후편이 제작되지 않아서 너무 아쉽네요ㅜㅜ','걍~ 재미있게 봤던 영화인데',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (144,'1926년에 볼드모트가 태어났는데 배경이 1926년이라는점ㅋ',null,'해리포터랑은 약간 다른느낌',null,'이 세기에 안태어났었으면 이 시리즈들을 못봤을텐데.. 정말 행운');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (145,null,'정말 거짓말 안하고 진짜 명작',null,'엔딩이 되게 깔끔하게 느껴짐','말도 안된다고 생각할 수 있다. 그러나 스토리가 쩔면 용서 된다');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (146,null,'에바그린은 진리!','능력들 또한 각기 매력! 동화적인 요소도 기대이상~','놀라운 상상력에 무릅을 탁 칩니다!',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (147,'영화에 대해 무슨 말이 필요한가~!',null,'죽기 전에 이 영화를 봐서 정말 다행이다!','이 영화는 영화계의 클래식이 될 것이다.',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (148,null,null,'졸작은 절대 아님ㅋㅋㅋㅋ','큰기대하지말고 신화좋아하면 보세요','나름 준수하게 볼만함');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (149,'진짜 원작 만화가 아깝다!~',null,'만화로 그냥 끝네지ㅡㅡ','이거 보고 친구에게 두고두고 욕 먹고있음ㅎ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (150,'D.C 스케일과 그래픽 더욱 업그레이드 된 액션','크립톤 행성의 비쥬얼은 굿',null,null,'깔끔하게 잘만들었다.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (183,'탐정부터 권상우 코믹연기 물오른듯 ㅋㅋ','2시간 순삭 설에 가족들이랑 한번 더 볼꺼임ㅋ','진짜계속웃으며봄ㅋㅋ배우들 티키타카란~무엇ㅋ',null,null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (33,'어디서 웃어야 할까요?','코믹요소를 넣으려고 한 거 같은데 전혀 웃기지도 않고 최악입니다ㅜㅜ',null,null,'뭐라고 써야할지 모르겠어요... 이런 한국영화 오랜만이네요 ㅠㅠ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (40,'음... 볼만했던 영화??','휴먼 코미디 대작. 웃고 울다보니 2시간이 후딱 가버림..',null,null,'기대 안했는데 생각보다 너무 재밌게 잘 봄');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (42,null,null,'하.. 유치뽕짝의 향연이었다..','매튜본은 천재인가바 콜린퍼스 왤케 섹시함?','젠틀하고 매너있게 약빨은 영화 ㅋㅋ');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (43,null,'한줄로 표현하면 말 많고 미친 또라인데 웃긴놈임.','엄마아빠랑 보러가면 시원하게 못웃음','번역가한데 상 하나 줘야한다',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (48,null,null,'다보고 나면 남는게 하나도없는 영화.. 평점9.2는 말도안된다..','윤계상은 이제 배우라 불러도 손색없을듯! ','천만영화나왔네핵잼있는영화');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (49,' 와 진짜 시간가는줄 모르고봄... 정우성 개멋있다~','어려서부터 많이 보던 복수 패턴ㅜㅜ',null,null,'후속편이 기다려집니다~~');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (99,'손예진 배우의 깨발랄~~~ㅋㅋ 새로운 느낌~ㅋ',null,'유쾌하면서도 포근하고 따뜻한 분위기까지 좋앗던 드라마~~~',null,'여신님 보러왓음~');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (53,null,'좀비가 무서운게아니라 사람이무섭다는걸 알려주는영화',null,'그냥 한국형 좀비물이 어색하지 않았다는 거에 큰 점수를 주며 앞으로의 한국영화를 기대해봅니다.','영화가 너무 비현실적이네요...공유 얼굴이!;!;');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (100,null,'일주일이 빨리빨리 지나갔으면~~ 얼릉 보고싶어요~~;','영상미 쵝오~','배경과 배우들의 의상,소품 하나하나까지 하나의 그림인줄~~~~',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (62,'성인들의 향수를 일깨우는 판타지...','도깨비..너무너무좋아요^^♡슬퍼요ㅜㅜ',null,null,'도깨비 깨앓이 하는중.,.');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (68,'몇번이나 봤지만 감명깊은 영화..',null,'이 영화를 안 본 사람이 너무 부럽다. 내가 처음 봤을 때의 그 감동을 느낄 수 있는 기회가 있으니..',null,'인생 중 세시간은 의무적으로 이 영화에 투자해야한다');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (78,null,'이 영화가 재미없다면 불쌍한 청춘',null,'첫사랑을 떠올릴 수 있는 아련한 기억의 습작...','남자를 미치게 만드는영화');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (102,'무슨 말이 필요한가 ...','인셉션은 대단하다 느꼈는데, 인터스텔라는 경이롭다고 느껴진다.',null,null,'기발한 상상력에 박수를!~');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (103,'마지막 반전을 위한 지루한 여행ㅡㅡ',null,'클로버필드는 역시 결말이야..',' 타의 추종을 불허하는 결말..',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (104,null,null,'인터스텔라가 100점이면, 마션은 50점..','그냥보세요 돈 안아깝습니다..','화성판 삼시세끼...');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (105,null,'영화적 메시지가 돋보이네요..','ㅇㅏ최악이다 잔인하고 내용 초반 중반 후반 갈길못잡고 엔딩은 개삼류고 돈아깝다','다들설국열차볼때 꼭양갱을사세욬ㅋㅋㅋ양갱드시면서봐보세욬ㅋㅋㅋ',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (106,'재난영화중 손꼽힘',null,'비슷한 소재의 “아마겟돈”에 비해서는 시각적 효과가 다소 약하네~~','억지스러운 아마겟돈보다, 훨씬 과학적이고 감동적인 딥 임팩트를 보시라',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (110,'보이스피싱에 낚여 지구에온 외계인들이 극안무도한 인간들에게 털리는 영화',null,'웬만하면 딴 영화 보세요','욱일 승천기때문에 토나온다',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (111,'체르노빌 갠적으로 멋있는 로봇인데 몇방에 지다니ㅜㅜ','로봇영화 좋아하는 사람들 이 좋아 하겠내요 굿입니다','영화요약 : 쿠광쾅쾅 쿠광쾅쾅 쿠광쾅쾅 펑 펑 끝ㅋㅋ',null,null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (112,null,null,'너무고차원적인 이야기','인류는 USB로 진화한다ㅋㅋ','1 더하기 1은 2가 아니다. 인간은 우리 스스로를 제한하고 있다');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (113,'문과판 인터스텔라라는 말이 이해가 된다','조한슨 음악은 만점',null,null,'당신은 이미 끝을 알면서 무엇을 시작하겠다고 마음 먹을 수 있습니까?');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (114,null,'밀리터리 좋아하시는 분들 강추','이거보면 해병대되고싶다는생각이들음','이거 10번이나봄....전쟁이랑 외계인이랑잘섞임',null);
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (115,'단순 오락영화가 아니라 자본주의 비판과 의식있는 영화',null,'감독 믿고 봤다 기대만큼 만족한 영화!',null,'과학이 발달한 세상에 1%를 위한 엘리시움');
Insert into MOVIE_COMMENT (MOVIE_ID,SUN,DRAGON,FIRE,JOY,STONE) values (116,null,'웬만하면 보는데 이건 진짜 보기힘든수준',null,'친구들과 함께라면 자신의 한계를 뛰어 넘을 수 있다ㅋㅋ','애들의 입에서 너무 쓰레기 대사ㅠㅠ');
