-- WebflexMain.sql
--메인 테이블 시퀀스넘버
create sequence main_no_seq
start with 1
increment by 1
nocache;

update MOVIE_MAIN set movie_card_back_path = REPLACE(movie_card_back_path, 'mp4', 'jpg')

FROM   movie_main;

select * from movie_user 

--메인 테이블
create table movie_main(
movie_id int primary key,
movie_title varchar2(500) not null,
movie_sub_title varchar2(200),
movie_poster_path varchar2(1000) not null, 
movie_category varchar2(100) not null,
movie_content varchar2(4000) not null,
movie_rating varchar2(100) not null,
movie_like varchar2(1) default 0,
movie_card_back_path varchar2(1000) not null,
movie_card_video_path varchar2(1000) not null,
movie_actor varchar2(500),
inputdate date
);
insert into MOVIE_MAIN (movie_id,movie_title,movie_sub_title,movie_poster_path,movie_category,movie_content,movie_rating,movie_card_back_path,movie_card_video_path,movie_actor) 
values(main_no_seq.nextval,#{movieTitle},#{movieSubTitle},#{moviePosterPath},#{movieCategory},#{movieContent},#{movieRating},#{movieCardBackPath},#{movieCardVideoPath},#{movieActor});
--코멘트
create table movie_comment(
movie_id int primary key,
sun varchar2(200),
dragon varchar2(200),
fire varchar2(200),
joy varchar2(200),
stone varchar2(200),
constraint fk_movie_id foreign key (movie_id) references movie_main(movie_id)
);

select * from movie_main;
delete from movie_main where movie_title = 'test';
select * from movie_main order by movie_id desc;
select * from movie_main;



Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (67,'노트북','The Notebook','/resources/images/mainPoster/노트북.jpg','romance','니콜라스 스파크스의 베스트셀러 소설을 영화화한 작품으로 1940년대 신분 차이와 전쟁으로 헤어져야 했던 젊은 연인의 이야기를 그렸다.','15세관람가','0','/resources/images/subPoster/노트북.jpg','/resources/images/movie_trailer/노트북.mp4','라이언 고슬링, 레이첼 맥아담스, 제임스 가너',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (98,'이태원 클라쓰','Itaewon Class','/resources/images/mainPoster/이태원클라쓰.jpg','drama','활력과 욕망이 넘치는 이태원. 한 전과자와 친구들이 꿈을 위해 뭉쳤다. 일단 시작은 술집 창업. 불합리한 세상, 막강한 적이 앞길을 막으면? 기를 쓰고 맞서 싸워야지!','15세관람가 ','0','/resources/images/subPoster/이태원클라쓰.jpg','/resources/images/movie_trailer/이태원 클라쓰.mp4','박서준, 김다미, 유재명',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (106,'딥 임팩트','Deep Impact','/resources/images/mainPoster/딥임팩트.jpg','SF','거대 혜성이 지구를 향해 돌진해온다! 온 인류의 운명은 혜성을 폭파하라는 대통령의 특명을 받은 전직 우주비행사의 손에 달렸다.','15세관람가','0','/resources/images/subPoster/딥임팩트.jpg','/resources/images/movie_trailer/딥임팩트.mp4','로버트 듀발, 테아 레오니, 일라이저 우드',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (110,'배틀쉽','Battleship','/resources/images/mainPoster/배틀쉽.jpg','SF','해상 훈련이 한창인 바다에 괴물체가 나타난다. 가공할 위력의 장벽을 구축하고 침공을 시작한 그들은, 우리가 그토록 찾아 헤맸던 외계의 생명체들. 어둠이 지배하는 미지의 세계 바다에서, 지구의 운명을 건 최후의 결전이 시작된다.','12세관람가 ','0','/resources/images/subPoster/배틀쉽.jpg','/resources/images/movie_trailer/배틀쉽.mp4','테일러 키치, 알렉산데르 스카르스고르드, 리한나',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (112,'루시','Lucy','/resources/images/mainPoster/루시.jpg','SF','범죄 조직의 협박으로 몸속에 정체불명의 약물을 넣어 운반하게 된 여자. 배 안에 든 주머니가 터지면서 약물이 온몸으로 퍼지자, 그 누구도 상상하지 못했던 엄청난 능력이 고개를 든다. 그녀는 이 초인적 능력으로 무엇을 할 수 있을까.','18세관람가','0','/resources/images/subPoster/루시.jpg','/resources/images/movie_trailer/루시.mp4','스칼렛 요한슨, 모건 프리먼, 최민식',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (114,'월드 인베이젼','Battle: Los Angeles','/resources/images/mainPoster/월드인베이젼.jpg','SF','외계인 침공으로 인류의 생존이 위협받는 가운데, 노련한 하사가 용감무쌍한 해병대를 이끌고 인류의 미래를 지켜내고자 한다.','12세관람가 ','0','/resources/images/subPoster/월드인베이젼.jpg','/resources/images/movie_trailer/월드인베이젼.mp4','아론 에크하트, 미셸 로드리게즈, 레이먼 로드리게즈',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (111,'퍼시픽 림','Pacific Rim','/resources/images/mainPoster/퍼시픽림.jpg','SF','바다 외계 생명체에 맞선 세계 동맹이 실패로 끝나면서 전직 파일럿과 새내기 파일럿이 힘을 합쳐 지구를 구하려 한다.','12세관람가','0','/resources/images/subPoster/퍼시픽림.jpg','/resources/images/movie_trailer/퍼시픽 림.mp4','찰리 허넘, 이드리스 엘바, 키쿠치 린코',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (113,'컨택트','Arrival','/resources/images/mainPoster/컨택트.jpg','SF','어느 날 지구에 나타난 의문의 존재로 전 세계가 혼란에 빠진다. 최고의 언어학자가 외계인들과의 소통에 나서지만 시간이 없다! 그들이 지구에 온 이유, 알아낼 수 있을까.','12세관람가 ','0','/resources/images/subPoster/컨택트.jpg','/resources/images/movie_trailer/컨택트.mp4','마크 오브라이언, 프랭크 스코피언, 에이미 애덤스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (115,'엘리시움','Elysium','/resources/images/mainPoster/엘리시움.jpg','SF','부자들이 초호화 우주 도시로 이주한 사이, 지구에 남겨진 이들의 삶은 점점 더 황폐해진다. 2154년을 배경으로 펼쳐지는 디스토피아 스릴러 영화.','18세관람가 ','0','/resources/images/subPoster/엘리시움.jpg','/resources/images/movie_trailer/엘리시움.mp4','맷 데이먼, 조디 포스터, 샬토 코플리',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (116,'림 오브 더 월드','Rim of the World','/resources/images/mainPoster/림 오브 더 월드.jpg','SF','외계인이 지구를 침공했다. 여름 캠프장에 고립된 네 명의 10대, 그들에게 떨어진 위험천만한 임무. 성격도 관심사도 제각각인데, 똘똘 뭉쳐서 세상을 구할 수 있으려나?','15세관람가 ','0','/resources/images/subPoster/림 오브 더 월드.jpg','/resources/images/movie_trailer/림오브더월드.mp4','잭 고어, 미야 체크, 벤저민 플로레스 주니어',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (117,'어스','Us','/resources/images/mainPoster/어스.jpg','thriller','해변으로 휴가를 온 가족. 엄마 애들레이드는 불안해진다. 어린 시절 섬뜩한 일이 벌어졌던 장소이기에. 그런데 그날 밤, 숙소 앞에 한 가족이 나타난다. 그녀의 가족과 똑같이 생긴 사람들이. 당신들은 누구인가, 아니, 우리는 누구인가?','15세관람가 ','0','/resources/images/subPoster/어스.jpg','/resources/images/movie_trailer/어스.mp4','루피타 뇽오, 윈스턴 듀크, 엘리자베스 모스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (119,'목격자','The Witness ','/resources/images/mainPoster/목격자.jpg','thriller',' 당신이 범죄 현장을 목격한다면? 어렵게 장만한 아파트로 이사 온 상훈. 우연히 살인 현장을 목격해 하루아침에 살인범의 표적이 되지만, 가족의 안위를 위해서도 사실을 발설할 수 없다. 그는 계속해서 익명 속의 방관자로 남게 될까.','15세관람가 ','0','/resources/images/subPoster/목격자.jpg','/resources/images/movie_trailer/목격자.mp4','이성민, 김상호, 곽시양',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (121,'사바하','Svaha: The Sixth Finger','/resources/images/mainPoster/사바하.jpg','thriller','전국에서 일어나는 이단 사건을 파헤치는 목사. 그가 수상한 신흥종교를 포착한다. 지금껏 겪은 사이비 종교와는 확연히 다른 사슴 동산. 그 시작과 끝엔 무엇이 있을까.','15세관람가 ','0','/resources/images/subPoster/사바하.jpg','/resources/images/movie_trailer/사바하.mp4','이정재, 박정민, 이재인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (122,'숨바꼭질','Hide and Seek','/resources/images/mainPoster/숨바꼭질.jpg','thriller','유복한 삶을 누리던 성수는 실종된 형의 누추한 아파트를 찾았다가 의문의 표식과 심상치 않은 이웃 주민들의 공포를 목격한다. 곧 그의 삶도 송두리째 흔들린다.','15세관람가 ','0','/resources/images/subPoster/숨바꼭질.jpg','/resources/images/movie_trailer/숨바꼭질.mp4','손현주, 전미선, 문정희',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (123,'더 링크','The Binding, Il legame','/resources/images/mainPoster/더링크.jpg','thriller','이탈리아 남부의 고택. 딸과 같이 이곳에 약혼자의 가족을 만나러 온 엠마는 불길한 기운에 휩싸인다. 그리고 딸에게 일어나는 기괴한 일들. 이 모든 것은 과거의 저주와 연관되어 있다. 딸을 앗아가려는 저주에 맞서려면 어째야 한단 말인가.','18세관람가','0','/resources/images/subPoster/더링크.jpg','/resources/images/movie_trailer/더 링크.mp4','리카르도 스카마르초, 미아 마에스트로',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (45,'6 언더그라운드','6 Underground','/resources/images/mainPoster/6언더그라운드.jpg','action','죽음을 위장하고 사라진 억만장자. 그가 전 세계에서 최정예 요원들을 선발한다. 6인의 고스트를 기다리는 대담하고 무모한 작전. 잔인한 독재자의 피로 세상을 물들여라!','18세관람가 ','0','/resources/images/subPoster/6언더그라운드.jpg','/resources/images/movie_trailer/6 언더그라운드.mp4','라이언 레이놀즈, 멜라니 로랑, 코리 호킨스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (80,'남자가 사랑할 때','Man In Love','/resources/images/mainPoster/남자가 사랑할 때.jpg','romance','건달 태일은 사채를 쓴 호정에게 돈을 받으러 갔다가 첫눈에 반한다. 만나주면 빚을 탕감해 주겠다며 다가가고 새 출발을 꿈꾸지만 사랑도 아픔도 이제 시작일 뿐.','15세관람가','0','/resources/images/subPoster/남자가 사랑할 때.jpg','/resources/images/movie_trailer/남자가 사랑 할 때.mp4','황정민, 한혜진, 남일우',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (78,'건축학개론','Architecture 101','/resources/images/mainPoster/건축학개론.jpg','romance','서연과 승민은 건축학 개론 수업에서 만나 사랑에 빠졌었다. 서연이 승민을 찾아와 꿈에 그리던 집을 지어 달라고 하고 둘 사이엔 다시 사랑이 싹튼다.','12세관람가','0','/resources/images/subPoster/건축학개론.jpg','/resources/images/movie_trailer/건축학개론.mp4','엄태웅, 한가인, 이제훈',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (79,'지금,만나러갑니다',' いま、?いにゆきます, Be with You','/resources/images/mainPoster/지금,만나러갑니다.jpg','romance','비의 계절에 돌아온다는 약속을 남기고 세상을 떠난 그녀, 비와 함께 돌아왔다. 그러나 그녀의 기억은 지워진 상태. 남편이 첫 만남부터 천천히 사랑의 기억을 복기해주자 다시 기적 같은 사랑이 시작된다. 하지만 비의 계절은 끝나 간다.','12세관람가','0','/resources/images/subPoster/지금,만나러갑니다.jpg','/resources/images/movie_trailer/지금, 만나러갑니다.mp4','다케우치 유코, 나카무라 시도, 다케이 아카시',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (104,'마션','The Martian','/resources/images/mainPoster/마션.jpg','SF','임무 중 모래폭풍을 만난 NASA 화성 탐사대. 동료 대원 마크가 사망했다고 판단해 지구로 귀환한다. 하지만 마크는 기적적으로 살아나 화성에 홀로 남았다. 이대로 포기할까? 아니, 여기선 안 죽어. 화성에서 살아남기, 이제 시작이다..','12세관람가 ','0','/resources/images/subPoster/마션.jpg','/resources/images/movie_trailer/마션.mp4','맷 데이먼, 제시카 채스테인, 크리스틴 위그인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (89,'오늘의 연애','Love Forecast','/resources/images/mainPoster/오늘의연애.jpg','romance','미모의 기상캐스터 현우와 늘 차이기만 하는 교사 준수는 18년 지기 친구. 편하지만 묘하게 끌리고, 사귀는 건 아니지만 각별한 두 사람. 하지만 언제까지 썸만 탈 것인가?','15세관람가','0','/resources/images/subPoster/오늘의연애.jpg','/resources/images/movie_trailer/오늘의 연애.mp4','이승기, 문채원, 이서진',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (102,'인터스텔라','Interstellar','/resources/images/mainPoster/인터스텔라.jpg','SF','인류 멸망이 목전에 닥친 미래. 우주비행사들이 웜홀을 통해 광활한 우주를 여행하며 인류가 살 수 있는 또 다른 행성을 찾아 나선다.','12세관람가 ','0','/resources/images/subPoster/인터스텔라.jpg','/resources/images/movie_trailer/인터스텔라.mp4','매튜 맥커너히, 앤 해서웨이, 제시카 채스테인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (124,'호텔 뭄바이','Hotel Mumbai','/resources/images/mainPoster/호텔뭄바이.jpg','thriller','2008년 인도 뭄바이, 웅장하고 화려한 타지 호텔에 일군의 사람이 모여든다. 이윽고 시작되는 나흘간의 악몽. 테러 공격의 표적이 된 이들의 처절한 실화가 펼쳐진다.','15세관람가','0','/resources/images/subPoster/호텔뭄바이.jpg','/resources/images/movie_trailer/호텔뭄바이.mp4','데브 파텔, 아미 해머, 틸다 코범-허비',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (125,'언더 워터','The Shallows','/resources/images/mainPoster/언더 워터.jpg','thriller','인적이 뜸한 외딴 해변. 홀로 파도를 타던 서퍼가 백상아리의 공격을 받았다. 암초 위에서 피를 흘리며 목숨만 부지하는 상황. 구조를 기대할 수 없으니 살아남을 방법은 하나뿐이다. 상어의 허점을 간파해, 있는 힘껏 헤엄치는 것.','15세관람가','0','/resources/images/subPoster/언더 워터.jpg','/resources/images/movie_trailer/언더 워터.mp4','블레이크 라이블리, 오스카르 하에나다, 앙헬로 호수에 로사노 코르소',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (126,'제럴드의 게임','Gerald`s Game','/resources/images/mainPoster/제럴드의 게임.jpg','thriller','어긋난 섹스 게임, 외딴 별장에 홀로 남겨진 아내. 침대에 결박된 채로, 그녀는 뒤틀린 환상과 어두운 비밀에 휩싸인다. 그리고 피하고 싶은 선택의 순간이 다가온다.','18세관람가','0','/resources/images/subPoster/제럴드의 게임.jpg','/resources/images/movie_trailer/제럴드의 게임.mp4','칼라 구지노, 브루스 그린우드 헨리 토머스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (127,'프로메테우스','Prometheus','/resources/images/mainPoster/프로메테우스.jpg','thriller','고대 유물에서 그들의 초대장이 발견됐다. 인류의 기원을 찾아 외계 행성으로 출발하는 과학 탐사선 프로메테우스. 그러나 기나긴 여정 끝에 그들을 깨운 대가는 가히 참혹했으니. 미래에 대한 충격 예언, 인류는 받아들일 수 있겠는가.','15세관람가','0','/resources/images/subPoster/프로메테우스.jpg','/resources/images/movie_trailer/프로메테우스.mp4','누미 라파스, 마이클 패스벤더, 샤를리즈 테론',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (128,'컨저링 2','The Conjuring 2','/resources/images/mainPoster/컨저링 2.jpg','thriller','네 아이와 엄마가 사는 런던의 집. 보이지 않는 손이 문을 두드리고, 가구들이 제멋대로 움직인다. 악령의 소행인가, 악령보다 더 사악한 인간의 짓인가. 초현실 현상 전문가 워런 부부의 실제 미스터리 사건 파일을 바탕으로 했다.','15세관람가','0','/resources/images/subPoster/컨저링 2.jpg','/resources/images/movie_trailer/컨저링2.mp4','패트릭 윌슨, 베라 파미가, 매디슨 울프',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (129,'엑소시즘 오브 에밀리 로즈','The Exorcism of Emily Rose','/resources/images/mainPoster/엑소시즘 오브 에밀리 로즈.jpg','thriller','엑소시즘을 행하다가 과실치사 혐의로 기소된 신부의 변론을 맡은 무신론자 변호사가 놀랍게도 점차 의뢰인의 말을 믿게 된다.','12세관람가','0','/resources/images/subPoster/엑소시즘 오브 에밀리 로즈.jpg','/resources/images/movie_trailer/엑소시즘 오브 에밀리 로즈.mp4','로라 리니, 톰 윌킨슨, 캠벨 스코트',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (130,'장산범','The Mimic','/resources/images/mainPoster/장산범.jpg','thriller','아들을 잃고 장산으로 이주한 가족. 숲속에서 한 소녀를 발견하고 집으로 데려온다. 마침내 입을 연 소녀. 그런데 목소리가 딸과 똑같다. 소녀의 진짜 목소리인가, 딸의 목소리를 흉내 내는 것인가. 익숙한 소리가 들린다면, 홀리지 마라.','15세관람가','0','/resources/images/subPoster/장산범.jpg','/resources/images/movie_trailer/장산범.mp4','염정아, 박혁권, 허진',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (131,'쿵푸 팬더 2','Kung Fu Panda 2','/resources/images/mainPoster/쿵푸 팬더 2.jpg','animation','새로운 무서운 적이 등장하자, 포와 무적의 오인방은 중국과 쿵푸를 지키기 위한 아슬아슬한 여정을 시작한다.','전체관람가','0','/resources/images/subPoster/쿵푸 팬더 2.jpg','/resources/images/movie_trailer/쿵푸 팬더2.mp4','잭 블랙, 안젤리나 졸리, 더스틴 호프먼',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (33,'미스터 주: 사라진 VIP','Mr.Zoo: The Missing VIP','/resources/images/mainPoster/미스터주사라진VIP.jpg','comedy','중대한 VIP 경호 임무에 실패하고 부상까지 당한 정보국 요원. 눈을 뜨니 온 세상 동물이 말을 한다. 이게 말이 돼? 이왕 이렇게 된 거, VIP 수색에 동물 녀석들의 도움이나 받자. 자 그럼, 인간과 동물의 합동 수사 시작이다!','12세 관람가','0','/resources/images/subPoster/미스터주사라진VIP.jpg','/resources/images/movie_trailer/미스터 주 - 사라진 VIP.mp4','이성민, 신하균, 김서형',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (34,'키싱 부스','The Kissing Booth','/resources/images/mainPoster/키싱부스1.jpg','comedy','첫 키스를 해버린 엘, 그것도 학교의 인기 넘버원하고! 하지만 그는 넘봐선 안 될 사람. 그와 사랑에 빠지면 평생의 단짝을 잃게 된다. 새가슴 엘의 선택은?','18세 관람가','0','/resources/images/subPoster/키싱부스1.jpg','/resources/images/movie_trailer/키싱 부스.mp4',' 조이 킹, 조엘 코트리, 제이컵 엘로디',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (35,'베테랑','Veteran','/resources/images/mainPoster/베테랑.jpg','comedy','법보다 돈이 더 강한 세상. 정의감으로 똘똘 뭉친 베테랑 형사와 돈으로 죄를 덮으려는 안하무인 재벌 3세. 한 치의 양보도 없는 두 사람의 불꽃 튀는 대결이 지금 시작된다!','15세 관람가','0','/resources/images/subPoster/베테랑.jpg','/resources/images/movie_trailer/베테랑.mp4','황정민, 유아인, 유해진',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (39,'세븐틴 어게인','17 Again','/resources/images/mainPoster/세븐틴어게인.jpg','comedy','중년의 위기에 가까워진 30대 마이크는 ‘다시 태어나기’를 바라고 있다. 그러던 어느 날 눈을 떠보니 다시 17살이 된 자신을 발견하게 되는데...','15세 관람가','0','/resources/images/subPoster/세븐틴어게인.jpg','/resources/images/movie_trailer/세븐틴 어게인.mp4','잭 에프론, 레슬리 맨, 매튜 페리',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (37,'키싱 부스2','The Kissing Booth2','/resources/images/mainPoster/키싱부스2.jpg','comedy','대학 입시 준비는 기본, 노아와의 장거리 연애에서 리와의 우정까지? 모든 걸 잘 해내고 싶은 엘. 그녀의 복잡한 일상에 매력 넘치는 남학생까지 등장하니, 하늘이 노랗다!','15세 관람가','0','/resources/images/subPoster/키싱부스2.jpg','/resources/images/movie_trailer/키싱 부스2.mp4','조이 킹, 조엘 코트리, 제이컵 엘로디',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (41,'맨 인 블랙: 인터내셔널','Men in Black: International','/resources/images/mainPoster/맨인블랙인터내셔널.jpg','comedy','나쁜 외계인 때려잡는 조직 맨 인 블랙, 일명 MIB. 이곳 최고의 에이스 요원과 생초짜 수습이 뭉쳤다. 외계 악당은 나날이 강력해지고, MIB는 수렁으로 빠져드는 난국. 우리의 신흥 듀오는 세상도, 조직도 구할 수 있을는지?','12세 관람가','0','/resources/images/subPoster/맨인블랙인터내셔널.jpg','/resources/images/movie_trailer/맨 인 블랙 - 인터내셔널.mp4','크리스 헴스워스, 테사 톰프슨, 리엄 니슨',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (40,'미쓰 와이프','Wonderful Nightmare','/resources/images/mainPoster/미쓰와이프.jpg','comedy','능력 뿜뿜 잘나가는 싱글 변호사 연우. 불의의 사고로 일찍 죽게 된 그녀에게 환생의 기회가 주어진다. 한 달 동안 애 둘 딸린 아줌마로 지내라고요? 평범한 주부의 전쟁 같은 일상. 하지만 변호사 본성이 어딜 가나? 너희들 딱 걸렸어!','15세 관람가','0','/resources/images/subPoster/미쓰와이프.jpg','/resources/images/movie_trailer/미쓰 와이프.mp4','엄정화, 송승헌, 김상호',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (42,'킹스맨: 시크릿 에이전트','Kingsman: The Secret Service','/resources/images/mainPoster/킹스맨시크릿에이전트.jpg','comedy','일탈을 일삼는 문제 청년. 차를 훔치다 경찰에 잡힌 그는 세련된 신사의 도움으로 풀려난다. 신사의 실체는 첩보 기관 킹스맨의 베테랑 요원. 청년은 신사의 추천으로 킹스맨 면접에 참여하지만, 앞에 놓인 관문이 그리 만만치 않다.','18세 관람가','0','/resources/images/subPoster/킹스맨시크릿에이전트.jpg','/resources/images/movie_trailer/킹스맨 - 시크릿 에이전트.mp4','콜린 퍼스, 사무엘 L. 잭슨, 마크 스트롱',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (43,'데드풀','Deadpool','/resources/images/mainPoster/데드풀1.jpg','comedy',' 세상에 이런 히어로쯤 하나 괜찮잖아? 비밀 실험에 참여한 후 특별한 능력을 갖게 된 주인공. 쌔끈한 빨간 슈트에 찰진 드립 장착한 데드풀로 거듭난다. 파워는 어마무시, 책임감은 개나 줘버려. 어디 한번 놀아보실까? 뮤직 큐.','18세 관람가','0','/resources/images/subPoster/데드풀1.jpg','/resources/images/movie_trailer/데드풀.mp4','라이언 레이놀즈, 모레나 바카린, 에드스크레인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (47,'300: 제국의 부활','300: RISE OF AN EMPIRE','/resources/images/mainPoster/300제국의부활.jpg','action','아버지의 원수를 갚기 위해 신이 된 왕의 아들. 크세르크세스가 페르시아의 대군을 이끌고 그리스로 진격한다. 그리고 이에 맞서는 아테네의 장군 테미스토클레스. 그리스의 운명이 흔들리는 지금. 오직 죽음만이 끝낼 수 있는 혈투가 온다.','18세관람가 ','0','/resources/images/subPoster/300제국의부활.jpg','/resources/images/movie_trailer/300제국의부활.mp4','설리번 스테이플턴, 에바 그린, 리나 히디',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (48,'범죄도시','The Outlaws','/resources/images/mainPoster/범죄도시.jpg','action','극악무도한 범죄를 저지르며 시민들을 공포에 빠뜨린 신흥 범죄 조직. 이들이 나쁜 놈들 한방에 때려잡는 괴물 형사의 레이더망에 딱 걸렸다. 무자비한 악당들과 정의감 넘치는 강력반 형사들의 대결. 불꽃 튀는 현실 액션의 향연이 펼쳐진다.','18세관람가 ','0','/resources/images/subPoster/범죄도시.jpg','/resources/images/movie_trailer/범죄도시.mp4','마동석, 윤계상, 조재윤',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (49,'신의한수','The Divine Move','/resources/images/mainPoster/신의한수.jpg','action','단 한 번의 승부에 목숨까지 오가는 비정한 내기 바둑의 세계. 살인 누명을 쓰고 감옥살이를 하게 된 바둑 기사가 복수를 위해 돌아온다. 그래 기다려라, 받은 만큼 돌려주마.','18세관람가 ','0','/resources/images/subPoster/신의한수.jpg','/resources/images/movie_trailer/신의한수.mp4','정우성, 이범수, 안성기',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (55,'콘스탄틴','Constantine','/resources/images/mainPoster/콘스탄틴.jpg','action','인간 세상에 존재하는 천사와 악마를 구분할 수 있는 남자. 그에게 형사가 찾아와 동생의 죽음을 조사해 달라고 한다. 자살로만 보이는 사건. 하지만 그는 알아볼 수 있다. 그 안에 숨은 거대한 악마의 힘을. DC 코믹스 원작.','15세관람가 ','0','/resources/images/subPoster/콘스탄틴.jpg','/resources/images/movie_trailer/콘스탄틴.mp4','키아누 리브스, 레이첼 바이스, 샤이아 러버프',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (56,'수어사이드 스쿼드','Suicide Squad','/resources/images/mainPoster/수어사이드 스쿼드.jpg','action','정부가 비밀리에 악당 중 최악질만 모아 자살 특공대를 구성한다. 임무를 완수하면 형량 감소, 실패하면 죽음. 자유를 위해 도망칠 궁리만 하던 악당들이 괴생명체의 공격에 똘똘 뭉치기 시작한다. 교도소 탈출이고 뭐고, 일단 살고 보자고.','15세관람가 ','0','/resources/images/subPoster/수어사이드 스쿼드.jpg','/resources/images/movie_trailer/수어사이드 스쿼드.mp4','윌 스미스, 재러드 레토, 마고 로비',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (58,'에놀라 홈즈','Enola Holmes','/resources/images/mainPoster/에놀라홈즈.jpg','action','사라진 엄마를 찾아야 한다! 홈즈 가문답게 탐정 본능 장착하고 런던에 간 에놀라. 하지만 시작부터 도망자 신세의 귀족 청년과 엮여버렸다. 그 와중에 오빠 셜록까지 따돌려야 한다니. 미스터리 가득한 이 모험, 무사히 마칠 수 있을까?','12세관람가 ','0','/resources/images/subPoster/에놀라홈즈.jpg','/resources/images/movie_trailer/에놀라 홈즈.mp4','밀리 보비 브라운, 렌리 카빌, 샘 클래플린',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (31,'베드보이즈 포 라이프','Bad Boys for life','/resources/images/mainPoster/베드보이즈포라이프.jpg','comedy','베테랑 형사지만 열정은 그래로인 마이크. 하지만 오랜파트너 마커스는 쉬고 싶단다. 친구의 은퇴 만은 막으려던 마이크가 괴한의 급습을 당하고, 이를 계기로 다시 손잡은 두사람. 이대로 끝낼 순 없잖아','18세 관람가','0','/resources/images/subPoster/베드보이즈포라이프.jpg','/resources/images/movie_trailer/베드보이즈 포 라이프.mp4','월 스미스, 마틴 로런스, 베너사 허진스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (32,'가장 보통의 연애','Crazy Romance','/resources/images/mainPoster/가장보통의연애.jpg','comedy','술에 취해 모르는 사람이랑 2시간이나 통화하며 파혼의 아픔을 쏟아낸 남자. 근데 통화 상대가 직장 동료였을 줄이야. 게다가 이 동료의 이별 현장도 목격한다. 덕분에 각자의 연애사를 알게 된 두 남녀. 어쩐지 서로에게 맘이 가는걸?','15세 관람가','0','/resources/images/subPoster/가장보통의연애.jpg','/resources/images/movie_trailer/가장 보통의 연애.mp4','김래원, 공효진, 강기영',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (57,'올드 가드','The Old Guard','/resources/images/mainPoster/올드가드.jpg','action','그림자 속에서 살아온 고대의 전사들. 정의를 지키고자 숱한 세월 싸워왔다. 하지만 불멸의 삶이란 무겁고도 힘겨운 것. 세상 그 무엇도 영원히 계속되지는 않으리.','18세관람가 ','0','/resources/images/subPoster/올드가드.jpg','/resources/images/movie_trailer/올드 가드.mp4','샤를리즈 테론, 키키 레인, 마르완 켄자리',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (60,'슬기로운 의사생활','Hospital Playlist','/resources/images/mainPoster/슬기로운의사생활.jpg','drama','탄생과 죽음이 공존하는, 인생의 축소판이라고 불리는 병원에서 특별한 하루하루를 살아가는 사람들의 이야기를 그린 드라마','15세관람가 ','0','/resources/images/subPoster/슬기로운의사생활.jpg','/resources/images/movie_trailer/슬기로운 의사생활.mp4','조정석, 유연석, 정경호',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (61,'응답하라 1988','Reply 1988','/resources/images/mainPoster/응답하라1988.jpg','drama','1988년, 쌍문동 골목길. 즐거움과 아픔을 함께 나누던 다섯 친구가 있다. 동네에서 함께 자라 서로의 인생을 함께한 청춘들. 이들을 중심으로 다섯 가족의 따뜻한 이야기가 펼쳐진다.','15세관람가 ','0','/resources/images/subPoster/응답하라1988.jpg','/resources/images/movie_trailer/응답하라 1988.mp4','이혜리, 박보검, 류준열',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (62,'쓸쓸하고 찬란하神-도깨비','Guardian: The Lonely and Great God','/resources/images/mainPoster/도깨비.jpg','drama','저승사자를 다시 마주친 써니. 놓칠세라 붙잡고 이름을 묻지만 답을 듣지 못한다. 신은 작심한 듯 은탁을 집으로 데려간다. 그녀를 위한 선택, 늦기 전에 결행할 생각이다.','15세관람가 ','0','/resources/images/subPoster/도깨비.jpg','/resources/images/movie_trailer/도깨비.mp4','공유, 김고은, 이동욱',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (63,'사이코지만 괜찮아','It`s Okay to Not Be Okay','/resources/images/mainPoster/사이코지만괜찮아.jpg','drama','소년은 오늘도 악몽에서 깨어났어요. 형이 좋아하는 동화 작가 문영이 강태가 일하는 병원에 낭독회를 하러 온다. 그리고 그녀가 다짜고짜 묻는다. 혹시, 운명을 믿어요?','15세관람가 ','0','/resources/images/subPoster/사이코지만괜찮아.jpg','/resources/images/movie_trailer/사이코지만 괜찮아.mp4','김수현, 서예지, 오정세',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (65,'위쳐','The Witcher','/resources/images/mainPoster/위쳐.jpg','drama','세계적인 판타지 대작이 넷플릭스 시리즈로 다시 태어난다. 어둠과 위험의 세계, 진실은 어디에 있을까. 운명으로 묶인 그들. 위쳐와 마법사, 홀로 남은 공주의 싸움이 시작된다.','18세관람가 ','0','/resources/images/subPoster/위쳐.jpg','/resources/images/movie_trailer/위쳐.mp4','헨리 카빌, 애니아 철로트라, 프레이아 앨런',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (66,'워킹데드','The Walking Dead','/resources/images/mainPoster/워킹데드.jpg','drama','눈을 떠보니 세상은 좀비가 점령한 전쟁터. 어디로 갈 것인가, 어떻게 생존할 것인가. 현실이 지옥일 때 희망은 의미가 있는가. 살아남은 자들의 사투가 펼쳐진다.','18세관람가 ','0','/resources/images/subPoster/워킹데드.jpg','/resources/images/movie_trailer/워킹데드.mp4','앤드류 링컨, 스티븐 연, 노만 리더스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (68,'타이타닉','Titanic','/resources/images/mainPoster/타이타닉.jpg','romance','대부호와 원치 않는 약혼을 한 여자. 배에 오른 순간, 거부할 수 없는 운명의 남자를 만난다. 인생은 선물이라 했던가. 매 순간이 마법처럼 펼쳐지는 시간, 영원할 수 있을까.','15세관람가','0','/resources/images/subPoster/타이타닉.jpg','/resources/images/movie_trailer/타이타닉.mp4','레오나르도 디카프리오, 케이트 윈슬렛, 빌리 제인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (83,'내 머리 속의 지우개','A Moment to remember','/resources/images/mainPoster/내 머리 속의 지우개.jpg','romance','편의점에서의 첫 만남 이후 철수가 도둑맞은 수진의 가방을 찾아주며 시작된 인연. 사랑이 깊어질수록 수진의 기억은 희미해지고, 철수는 병원에서 충격적인 얘길 듣게 된다.','12세관람가','0','/resources/images/subPoster/내 머리 속의 지우개.jpg','/resources/images/movie_trailer/내 머리 속의 지우개.mp4','정우성, 손예진, 백종학',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (44,'마이펫의 이중생활 2','The Secret Life of Pets 2','/resources/images/mainPoster/마이펫의이중생활2.jpg','comedy','강아지, 고양이, 토끼, 이번엔 호랑이까지? 더욱더 대담해진 펫들의 시크릿 라이프. 똘똘 뭉치면 모든 것이 가능하다. 이번엔 어떤 모험을 떠나볼까나? 물론 인간에게는 비밀!','전체관람가','0','/resources/images/subPoster/마이펫의이중생활2.jpg','/resources/images/movie_trailer/마이펫의 이중생활2.mp4','패튼 오스왈트, 케빈 하트, 티퍼니 해디시',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (51,'월드 워 Z','World War Z','/resources/images/mainPoster/월드워z.jpg','action','UN 소속 조사관이 세계 곳곳에서 퍼지는 치명적인 좀비 바이러스를 막고자 시간, 운명과의 싸움을 벌인다.','15세관람가 ','0','/resources/images/subPoster/월드워z.jpg','/resources/images/movie_trailer/월드워z.mp4','브래드 피트, 미레유 에노스, 다니엘라 케르테스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (52,'아저씨','The Man from Nowhere','/resources/images/mainPoster/아저씨.jpg','action','아저씨, 깡패예요? 이름을 지우고 세상을 등진 전직 특수요원에게 유일하게 다가온 옆집 소녀. 그러나 마음을 열고 우정을 나눈 순간, 소녀가 무서운 세상 속으로 사라졌다!','18세관람가 ','0','/resources/images/subPoster/아저씨.jpg','/resources/images/movie_trailer/아저씨.mp4','원빈, 김새론, 김태훈',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (53,'부산행','Train to Busan','/resources/images/mainPoster/부산행.jpg','action','좀비 바이러스가 온 나라를 휩쓸면서, 단 하나 남은 안전한 도시로 가기 위해 딸과 함께 열차에 몸을 실은 남자. 살아남기 위한 극한의 사투가 시작된다','15세관람가 ','0','/resources/images/subPoster/부산행.jpg','/resources/images/movie_trailer/부산행.mp4','공유, 정유미, 마동석',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (54,'블레이드 러너 2049','Blade Runner 2049','/resources/images/mainPoster/블레이드러너2049.jpg','action','수십 년 만에 모습을 드러낸 유골에는 어떤 비밀이 숨어 있었나. 진실을 찾으려는 경찰, 진실을 덮으려는 조직, 진실을 악용하려는 재계 거물의 쫓고 쫓기는 게임이 시작된다!','15세관람가 ','0','/resources/images/subPoster/블레이드러너2049.jpg','/resources/images/movie_trailer/블레이드 러너 2049.mp4','라이언 고슬링, 해리슨 포드, 아나 데 아르마스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (88,'두번할까요','Love, Again','/resources/images/mainPoster/두번할까요.jpg','romance','성대한(?) 이혼식 이후 다시 싱글로 돌아온 선영과 현우. 이제 영원히 끝난 사이인 줄 알았는데, 칡넝쿨보다 질긴 것이 둘의 인연이었으니. 선영 앞에 현우의 친구 상철이 등장하면서, 세 남녀의 싱글라이프가 꼬일 대로 꼬이기 시작한다.','15세관람가','0','/resources/images/subPoster/두번할까요.jpg','/resources/images/movie_trailer/두번할까요.mp4','권상우, 이정현, 이종혁',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (95,'말할수없는비밀','不能說的秘密, Secret','/resources/images/mainPoster/말할수없는비밀.jpg','romance','예고로 전학 온 첫날, 교정에서 아름다운 피아노 선율이 들린다. 소리에 이끌려 문을 연 음악실. 거기 한 여학생이 있다. 첫눈에 사랑에 빠지지만 그녀는 홀연히 사라진다. 나타났다 사라지기를 반복하는 그녀. 그녀에게 더 다가가고 싶다.','12세관람가','0','/resources/images/subPoster/말할수없는비밀.jpg','/resources/images/movie_trailer/말할수없는비밀.mp4','쑹젠장, 황쥔랑, 잔휘하오',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (93,'오페라의 유령','The Phantom of the Opera','/resources/images/mainPoster/오페라유령.jpg','romance','그동안 수많은 사람의 마음을 울렸던 뮤지컬 《오페라의 유령》. 25주년을 맞아, 그 특별한 공연을 직접 스크린에 담았다. 감동과 전율이 가득한 무대, 기적과 같은 순간이 지금 눈앞에 펼쳐진다.','전체관람가','0','/resources/images/subPoster/오페라유령.jpg','/resources/images/movie_trailer/오페라의 유령.mp4','라민 카림루, 시에라 보게스, 해들리 프레이저',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (94,'나의 소녀시대','Our Times','/resources/images/mainPoster/나의소녀시대.jpg','romance','불량스러운 남고생과 똑똑하지만 어딘가 허당끼가 있는 여고생. 서로의 연애를 도와주기 위해 생각지 않은 동맹을 맺는다.','15세관람가','0','/resources/images/subPoster/나의소녀시대.jpg','/resources/images/movie_trailer/나의 소녀시대.mp4','송운화, 왕다루, 이옥새',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (96,'어바웃 타임','About Time','/resources/images/mainPoster/어바웃타임.jpg','romance','태솔로 팀(돔놀 글리슨)은 성인이 된 날, 아버지(빌 나이)로부터 놀랄만한 가문의 비밀을 듣게 된다.
 바로 시간을 되돌릴 수 있는 능력이 있다는 것!
 그것이 비록 히틀러를 죽이거나 여신과 뜨거운 사랑을 할 수는 없지만,
 여자친구는 만들어 줄 순 있으리.. ','전체관람가','0','/resources/images/subPoster/어바웃타임.jpg','/resources/images/movie_trailer/어바웃타임.mp4','도널 글리슨, 레이첼 맥아담스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (97,'SKY 캐슬','Sky Castle','/resources/images/mainPoster/SKY캐슬.jpg','drama','대한민국의 내로라하는 엘리트가 사는 SKY 캐슬. 누구보다 위에 올라 아래를 내려다보고 살아야 한다는 걸 한 번도 의심한 적 없는 삶은 어떨까. 겉으로는 화려하고 우아하지만, 속으로는 욕망과 시기로 가득 찬 이들의 이야기가 펼쳐진다.','15세관람가 ','0','/resources/images/subPoster/SKY캐슬.jpg','/resources/images/movie_trailer/SKY캐슬.mp4','염정아, 이태란, 정준호',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (99,'사랑의 불시착','Crash Landing on You','/resources/images/mainPoster/사랑의불시착.jpg','drama','뜻밖의 돌풍은 행운일까, 불운일까. 패러글라이딩 사고로 북한에 불시착한 재벌 딸. 그곳에서 깐깐한 북한군 장교를 만난다. 이 와중에 피어오르는 낯선 감정은 뭐지?','15세관람가 ','0','/resources/images/subPoster/사랑의불시착.jpg','/resources/images/movie_trailer/사랑의불시착.mp4','현빈, 손예진, 서지혜',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (100,'그 겨울, 바람이 분다','That Winter, The Wind Blows','/resources/images/mainPoster/그 겨울, 바람이 분다.jpg','drama','여자, 술, 포커가 인생의 전부인 사기꾼. 시각장애를 가진 재벌가 상속녀에게 접근해 한몫 챙길 심산이다. 하지만 자기를 닮은 그녀의 모습에 미묘한 감정을 느끼고, 계획에서 멀어지기 시작한다. 자신의 목숨이 걸린 일이란 것도 잊은 채.','15세관람가 ','0','/resources/images/subPoster/그 겨울, 바람이 분다.jpg','/resources/images/movie_trailer/그 겨울, 바람이 분다.mp4','조인성, 송혜교, 김범',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (103,'클로버필드 패러독스','The Cloverfield Paradox','/resources/images/mainPoster/클로버필드패러독스.jpg','SF','에너지 문제를 해결하기 위해 첨단 디바이스를 시험하던 우주정거장의 과학자들. 무시무시한 어둠의 대체현실을 마주한다.','15세관람가 ','0','/resources/images/subPoster/클로버필드패러독스.jpg','/resources/images/movie_trailer/클로버필드 패러독스.mp4','매튜 맥커너히, 앤 해서웨이, 제시카 채스테인',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (105,'설국열차','Snowpiercer','/resources/images/mainPoster/설국열차.jpg','SF','2031년 빙하기, 열차에 올라 삶을 이어가는 생존자들. 그러나 객실에서 재현되는 계급 간 불평등에 춥고 배고픈 꼬리칸의 불만이 터진다. 한 칸 한 칸 전진하라, 해방을 위해!','15세관람가','0','/resources/images/subPoster/설국열차.jpg','/resources/images/movie_trailer/설국열차.mp4','크리스 에반스, 송강호, 에드 해리스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (172,'종이의 집','La Casa de Papel','/resources/images/mainPoster/종이의집.jpg','drama','계획이 뜻대로 흘러가지 않자 팀은 언론을 통해 대중의 지지를 얻으려 하고, 인질들은 반격을 모의한다. 라켈은 애인과 더욱 가까워지는 한편, 교수를 잡을 함정을 판다.','18세관람가 ','0','/resources/images/subPoster/종이의집.jpg','/resources/images/movie_trailer/종이의 집.mp4','우르술라 코르베로, 알바로 모르테, 이치아르 이투뇨',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (171,'킹덤','Kingdom','/resources/images/mainPoster/킹텀.jpg','drama','병든 왕을 둘러싸고 흉흉한 소문이 떠돈다. 어둠에 뒤덮인 조선, 기이한 역병에 신음하는 산하. 정체 모를 악에 맞서 백성을 구원할 희망은 오직 세자뿐이다.','18세관람가 ','0','/resources/images/subPoster/킹텀.jpg','/resources/images/movie_trailer/킹텀.mp4','주지훈, 류승룡, 배두나',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (186,'형','MY ANNOYING BROTHER','/resources/images/mainPoster/형.jpg','comedy','“살다 보니까 니가 내 인생에 도움이 되는 날이 온다?” 뻔뻔한 사기꾼, 동생 핑계로 가석방의 기회를 물었다!','12세 관람가','0','/resources/images/subPoster/형.jpg','/resources/images/movie_trailer/형.mp4','조정석, 디오, 박신혜',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (137,'장화신은 고양이','Puss in Boots','/resources/images/mainPoster/장화신은 고양이.jpg','animation','전설의 장화신은 고양이가 거인의 성으로 진격한다. 목표는 황금알을 낳는 거위를 손에 넣는 것. 든든한(?) 동지들이여, 작전대로만 하자고. 난 거인을 맡을게. 너희는 황금알을 훔쳐!','전체관람가','0','/resources/images/subPoster/장화신은 고양이.jpg','/resources/images/movie_trailer/장화신은 고양이.mp4','안토니오 반데라스, 셀마 헤이엑, 캘리퍼내키스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (147,'반지의 제왕: 반지 원정대','The Lord of the Rings: The Fellowship of the Ring','/resources/images/mainPoster/반지의제왕-반지 원정대.jpg','fantasy','호빗들의 평화로운 마을에서부터 연기로 가득한 모르도르까지, 프로도 배긴스는 사우론의 반지를 파괴한다는 사명을 짊어지고 장대한 여정에 오른다.','12세관람가','0','/resources/images/subPoster/반지의제왕-반지 원정대.jpg','/resources/images/movie_trailer/반지의 제왕.mp4','일라이저 우드, 이언 매컬런, 비고 모텐스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (149,'라스트 에어벤더','The Last Airbender','/resources/images/mainPoster/라스트 에어벤더.jpg','fantasy','불의 제국은 평화롭기만 하던 공기, 물, 흙의 제국을 상대로 전쟁을 일으키고, 평화를 다시 찾을 수 있는 열쇠는 한 소년이 쥐고 있는데...','전체관람가','0','/resources/images/subPoster/라스트 에어벤더.jpg','/resources/images/movie_trailer/라스트 에어벤더.mp4','노아 링어, 데브 파텔, 니콜라 펠츠',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (150,'맨 오브 스틸','Man of Steel','/resources/images/mainPoster/맨 오브 스틸.jpg','fantasy','사악한 장군에게 위협받는 지구의 평화. 특별한 능력을 숨기고 살아온 클라크 켄트는 자신의 운명을 받아들이며 강철의 사나이 슈퍼맨으로 싸울 것을 결의한다.','12세관람가','0','/resources/images/subPoster/맨 오브 스틸.jpg','/resources/images/movie_trailer/맨 오브 스틸.mp4','헨리 카빌, 에이미 애덤스, 마이클 섀넌',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (151,'매드맥스: 분노의 도로','Mad Max: Fury Road','/resources/images/mainPoster/매드맥스-분노의 도로.jpg','fantasy','핵전쟁으로 황폐해진 세상을 정처 없이 떠돌던 맥스. 독재자의 폭정을 피해 도망치는 여전사와 독재자의 다섯 여인을 도와주게 되면서 광기에 찬 사막의 질주를 시작한다.','15세관람가','0','/resources/images/subPoster/매드맥스-분노의 도로.jpg','/resources/images/movie_trailer/매드맥스 - 분노의 도로.mp4','톰 하디, 샤를리즈 테론, 니컬러스 홀트',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (152,'헬보이 2: 골든 아미','Hellboy II: The Golden Army','/resources/images/mainPoster/헬보이 2- 골든 아미.jpg','fantasy','인간과 요괴의 휴전은 끝났다! 잠들어 있던 최강의 군단을 깨워 세상을 움켜쥐려는 요괴의 욕심이 협정을 깨버린 것. 이제 지구를 지키기 위해 헬보이와 동료들이 나설 차례!','12세관람가','0','/resources/images/subPoster/헬보이 2- 골든 아미.jpg','/resources/images/movie_trailer/헬보이2 - 골드 아미.mp4',' 론 펄먼, 셀마 블레어, 더그 존스',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (153,'미이라 3: 황제의 무덤','The Mummy: Tomb of the Dragon Emperor','/resources/images/mainPoster/미이라 3- 황제의 무덤.jpg','fantasy','2000년 전 중국 황제가 깨어났다! 다시 세계 정복을 노리는 황제의 야심, 게다가 이를 이용하려는 세력까지 나타났으니. 어쩔 도리 있나, 오코넬 가족이 움직이는 수밖에. 이연걸의 화려한 액션까지 더해진 《미이라》 세 번째 이야기!','12세관람가','0','/resources/images/subPoster/미이라 3- 황제의 무덤.jpg','/resources/images/movie_trailer/미이라 - 황제의 무덤.mp4','브렌든 프레이저, 이연걸, 마리아 벨로',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (157,'그 여자 작사 그 남자 작곡','Music and Lyrics','/resources/images/mainPoster/그 여자 작사 그 남자 작곡.jpg','music','재기를 꿈꾸며 작곡에 한창인 왕년의 팝스타. 공백이 너무 길었던 탓일까. 도통 악상이 떠오르지 않는다. 그때 혜성처럼 나타난 수다쟁이 아가씨. 입만 열면 주옥같은 가사를 내뱉는데. 둘이 함께라면 멋진 곡이 나올 것 같다!','12세관람가','0','/resources/images/subPoster/그 여자 작사 그 남자 작곡.jpg','/resources/images/movie_trailer/그 여자 작사 그 남자 작곡.mp4','휴 그랜트, 드루 배리모어, 브래드 개릿',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (158,'레미제라블','Les Mis?rables','/resources/images/mainPoster/레미제라블.jpg','music','19세기가 낳은 불멸의 고전, 빅토르 위고의 《레미제라블》. 1985년 최초로 뮤지컬로 제작된 이 위대한 소설이 스크린으로 찾아왔다. 프랑스 혁명 이후를 배경으로 장발장이라는 인물을 통해 사랑과 용서, 희생과 구원을 노래하는 작품.','12세관람가','0','/resources/images/subPoster/레미제라블.jpg','/resources/images/movie_trailer/레미제라블.mp4','휴 잭맨, 러셀 크로, 앤 해서웨이',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (159,'유열의 음악앨범','Tune in for Love','/resources/images/mainPoster/유열의 음악앨범.jpg','music','1994년, 동네 제과점에서 처음 만난 미수와 현우. 짧은 인연 뒤 안타깝게 헤어진 둘은 수년이 지나도록 서로를 찾으려 애쓴다. 하지만 운명은 그들을 계속 갈라놓는다.','12세관람가','0','/resources/images/subPoster/유열의 음악앨범.jpg','/resources/images/movie_trailer/유열의 음악앨범.mp4','김고은, 정해인, 박해준',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (163,'위플래쉬','Whiplash','/resources/images/mainPoster/위플래쉬.jpg','music','뉴욕의 명문 셰이퍼 음악학교에서
 최고의 스튜디오 밴드에 들어가게 된 신입생 앤드류, 최고의 연주를 위한 완벽한 스윙이 시작된다!','15세관람가','0','/resources/images/subPoster/위플래쉬.jpg','/resources/images/movie_trailer/위플래쉬.mp4','마일즈 텔러, J.K. 시몬스, 멜리사 베노이스트',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (166,'맘마미아','Mamma Mia!','/resources/images/mainPoster/맘마미아.jpg','music','결혼식 전날, 소피가 초대한 세 남자(샘,해리, 빌)가 그리스 섬에 도착하면서 도나는 당황하게 되는데... 과연 소피의 아빠는 누구일까? 그리고 이들의 결혼식은 무사히 끝날 수 있을까?','12세관람가','0','/resources/images/subPoster/맘마미아.jpg','/resources/images/movie_trailer/맘마미아.mp4','멜리 스트립, 아만다 사이프리드, 피어스 브로스넌',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (167,'위대한 쇼맨','The Greatest Showman','/resources/images/mainPoster/위대한쇼맨.jpg','music','쇼 비즈니스의 창시자이자, 꿈의 무대로 전세계를 매료시킨 남자 ‘바넘’의 이야기에서 영감을 받아 탄생한 오리지널 뮤지컬 영화 <위대한 쇼맨>.','12세관람가','0','/resources/images/subPoster/위대한쇼맨.jpg','/resources/images/movie_trailer/위대한 쇼맨.mp4','휴 잭맨, 잭 에프론, 미셸 윌리엄스',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (170,'알라딘','Aladdin','/resources/images/mainPoster/알라딘.jpg','music','머나먼 사막 속 신비의 아그라바 왕국의 시대.좀도둑 ‘알라딘’은 마법사 ‘자파’의 의뢰로 마법 램프를 찾아 나섰다가주인에게 세 가지 소원을 들어주는 지니를 만나게 되고, 자스민 공주의 마음을 얻으려다 생각도 못했던 모험에 휘말리게 되는데…','전체관람가','0','/resources/images/subPoster/알라딘.jpg','/resources/images/movie_trailer/아라딘.mp4','메나 마수드, 윌 스미스, 나오미 스콧',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (132,'슈퍼 배드 2','Despicable Me 2','/resources/images/mainPoster/슈퍼 배드 2.jpg','animation','슈퍼 악당 그루가 딸바보도 모자라 아름다운 파트너를 거느린 영웅이 되어 돌아온다! 세계 정복에 나선 최강 악당에게 맞선다는데 이건 웬 미니언들도 웃고 갈 소리?','전체관람가','0','/resources/images/subPoster/슈퍼 배드 2.jpg','/resources/images/movie_trailer/슈퍼배드2.mp4','스티브 커렐, 크리스틴 위그 , 벤저민 브랫',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (135,'앵그리버드 더 무비','The Angry Birds Movie','/resources/images/mainPoster/앵그리버드 더 무비.jpg','animation','분노 장애 치료라는 법정 최고형을 선고받은 레드. 피그들이 섬을 침략해 오자 억눌렀던 분노가 다시 고개를 든다. 에라, 모르겠다. 일단 우리 마을을 지키고 봐야 하는걸! 분노의 동지들이여, 나를 따르라!','전체관람가','0','/resources/images/subPoster/앵그리버드 더 무비.jpg','/resources/images/movie_trailer/앵그리버드 더 무비.mp4','제이슨 서데이키스, 조시 게드, 대니 맥브라이드',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (136,'마다가스카','Madagascar','/resources/images/mainPoster/마다가스카.jpg','animation','타고 있던 배가 전복되어 동물원에 있던 사자, 기린, 얼룩말 그리고 하마가 괴짜 동물들로 가득한 마다가스카 섬으로 표류하게 된다.','전체관람가','0','/resources/images/subPoster/마다가스카.jpg','/resources/images/movie_trailer/마다가스카.mp4','벤 스틸러, 크리스 록, 데이비드 슈위머',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (139,'터보','Turbo','/resources/images/mainPoster/터보.jpg','animation','세계 최고의 카레이서가 되는 것이 꿈인 달팽이, 터보. 우연한 사고로 빛의 속도로 달릴 수 있는 파워를 얻게 된다. 하지만 레이싱 경기에서 우승하려면 혼자서는 역부족인 듯한데. 우리의 터보는 레이싱 영웅이 되는 꿈을 이룰 수 있을까?','전체관람가','0','/resources/images/subPoster/터보.jpg','/resources/images/movie_trailer/터보.mp4','라이언 레이놀즈, 폴 지어마티, 새무엘 L.잭슨',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (140,'앨빈과 슈퍼밴드-악동 어드벤처','Turbo','/resources/images/mainPoster/앨빈과 슈퍼밴드-악동 어드벤처.jpg','animation','아빠가 청혼을 한다고? 그럼 우린? 둘 중 하나 아니겠어. 숲으로 내쫓기거나, 아빠 여자친구의 아들 그 못된 녀석과 형제가 되거나. 둘 다 받아들일 수 없다. 아빠의 청혼을 막으러 가자, 마이애미로! 일단 공항 검색대부터 통과하고.','전체관람가','0','/resources/images/subPoster/앨빈과 슈퍼밴드-악동 어드벤처.jpg','/resources/images/movie_trailer/앨빈과 슈퍼밴드 - 악동 어드벤처.mp4','저스틴 롱, 매투 그레이구블러, 제시 매카트니',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (141,'센과 치히로의 행방불명 ','Spirited Away','/resources/images/mainPoster/센과 치히로의 행방불명.jpg','animation','마녀가 지배하는 신비한 세계에 발을 들여놓은 치히로. 마녀에게 거역하는 자는 동물로 변하게 되는데...','전체관람가','0','/resources/images/subPoster/센과 치히로의 행방불명.jpg','/resources/images/movie_trailer/센과 치히로의 행방불명.mp4','히이라기 루미, 이리노미유, 나쓰키 마리',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (143,'황금 나침반','The Golden Compass','/resources/images/mainPoster/황금 나침반.jpg','fantasy','조던 대학의 기숙사에서 아무런 걱정 없이 생활하던 조숙한 고아 소녀 리라가 또 다른 세계를 찾아 머나먼 북극으로 여정을 떠난다.','전체관람가	','0','/resources/images/subPoster/황금 나침반.jpg','/resources/images/movie_trailer/황금 나침반.mp4','니콜 키드먼, 다니엘 크레이그, 다코타 블루 리차드',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (144,'신비한 동물사전','Fantastic Beasts and Where to Find Them','/resources/images/mainPoster/신비한 동물사전.jpg','fantasy','신비한 동물들을 가방에 넣고 다니는 괴짜 마법사 뉴트. 뉴욕에 도착하자마자 녀석들이 탈출을 감행한다. 덕분에 마법 의회에 쫓기게 된 그는 어둠의 존재 옵스큐러스와 맞닥뜨리는데. 그 존재의 이유는 마법 세계를 위험에 빠뜨리는 것.','12세관람가 ','0','/resources/images/subPoster/신비한 동물사전.jpg','/resources/images/movie_trailer/신비한 동물사전.mp4','에디 레드메인, 캐서린 워터스턴, 댄 포글러',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (145,'강철의 연금술사','FULLMETAL ALCHEMIST','/resources/images/mainPoster/강철의 연금술사.jpg','fantasy','강철의 연금술사 에드, 잃어버린 동생의 몸을 되찾기 위해 물불을 가리지 않는다. 두 형제를 지켜보는 군과 괴물 같은 존재들의 훼방에도 동생의 예전 모습을 찾을 수 있을까.','15세관람가 ','0','/resources/images/subPoster/강철의 연금술사.jpg','/resources/images/movie_trailer/강철의 연금술사.mp4','야마다 료스케, 혼다 쓰바사, 딘 후지오카',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (180,'테이큰3','Taken 3','/resources/images/mainPoster/테이큰3.jpg','action','모든 것이 끝난다! 리암 니슨 <테이큰> 시리즈 그 마지막 이야기
 전 부인 레니가 방문한다는 연락을 받고 집에 돌아온 브라이언 밀스(리암 니슨)
 그를 기다리는 것은 살해 당한 아내
 사태를 파악할 겨를도 없이 경찰이 들이닥치고
 브라이언은 살인범으로 체포되기 직전 탈출한다.','15세관람가 ','0','/resources/images/subPoster/테이큰3.jpg','/resources/images/movie_trailer/테이큰3.mp4','리암 니슨, 팜케 얀센, 매기 그레이스',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (156,'마스크','The Mask','/resources/images/mainPoster/마스크.jpg','fantasy','우연히 고대의 마스크를 발견한 평범한 은행원. 호기심에 써보자 초인적 힘이 솟구치고 무한대의 능력이 발휘된다. 감히 넘보지 못했던 여성의 마음도 사로잡게 되지만 짜릿한 경험도 잠시. 마스크가 초래한 소동이 걷잡을 수 없이 번진다.','15세관람가','0','/resources/images/subPoster/마스크.jpg','/resources/images/movie_trailer/마스크.mp4','짐 캐리, 카메론 디아즈, 피터 리거트',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (138,'슈렉 3','Shrek 3','/resources/images/mainPoster/슈렉3.jpg','animation','피오나와의 평화로운 삶도 잠시, 슈렉은 해롤드 왕이 갑자기 병이 들자 왕위 계승자를 찾아와야 하는 상황에 놓인다.','전체관람가','0','/resources/images/subPoster/슈렉3.jpg','/resources/images/movie_trailer/슈렉 3.mp4','마이크 마이어스, 에디머피, 카메론 디아즈',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (161,'어거스트 러쉬','August Rush','/resources/images/mainPoster/어거스트러쉬.jpg','music','그녀를 놓친 뒤, 열정을 잃은 밴드 보컬. 그와 헤어진 뒤, 아이까지 떠나보낸 첼리스트. 마법 같은 하룻밤 이후 긴 이별을 견뎌야 했던 두 사람에게 기적의 멜로디가 들려온다. 엄마와 아빠를 찾는 한 소년의 간절한 연주가 울려 퍼진다.','전체관람가','0','/resources/images/subPoster/어거스트러쉬.jpg','/resources/images/movie_trailer/어거스트 러쉬.mp4','프레디 하이모어, 케리러셀, 조나단 리스 마이어스',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (162,'보헤미안 랩소디','BOHEMIAN RHAPSODY','/resources/images/mainPoster/보헤미안 랩소디.jpg','music','공항에서 수하물 노동자로 일하며 음악의 꿈을 키우던 이민자 출신의 아웃사이더 ‘파록버사라’보컬을 구하던 로컬 밴드에 들어가게 되면서 ‘프레디 머큐리’라는 이름으로 밴드 ‘퀸’을 이끌게 된다.시대를 앞서가는 독창적인 음악과 화려한 퍼포먼스로 관중들을 사로잡으며 성장하던 ‘퀸’은 라디오와 방송에서 외면을 받을 것이라는 음반사의 반대에도 불구하고 무려 6분 동안 이어지는 실험적인 곡 ‘보헤미안 랩소디’로 대성공을 거두며 월드스타 반열에 오른다.그러나 독보적인 존재감을 뿜어내던 ‘프레디 머큐리’는 솔로 데뷔라는 유혹에 흔들리게 되고 결국 오랜 시간 함께 해왔던 멤버들과 결별을 선언하게 되는데…세상에서 소외된 아웃사이더에서 전설의 록밴드 ‘퀸’ 되기까지, 우리가 몰랐던 그들의 진짜 이야기가 시작된다!','12세관람가','0','/resources/images/subPoster/보헤미안 랩소디.jpg','/resources/images/movie_trailer/보헤미안 랩소디.mp4','라미 말렉, 루시 보인턴, 귈림 리',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (164,'원스','ONCE','/resources/images/mainPoster/원스.jpg','music','이제 사랑은 더 이상 없을 거라고 믿었던 ‘그’삶을 위해 꿈을 포기했던 ‘그녀’ 더블린의 밤거리에서 마법처럼 시작된 만남','전체관람가','0','/resources/images/subPoster/원스.jpg','/resources/images/movie_trailer/원스.mp4','글렌 핸사드, 마르게타 이글로바, 앨리이스테어 폴리',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (165,'비긴어게인','Begin Again','/resources/images/mainPoster/비긴어게인.jpg','music','스타 음반프로듀서였지만 이제는 해고된 ‘댄’은 미치기 일보직전 들른 뮤직바에서 그레타의 자작곡을 듣게 되고 아직 녹슬지 않은 촉을 살려 음반제작을 제안한다. 거리 밴드를 결성한 그들은 뉴욕의 거리를 스튜디오 삼아 진짜로 부르고 싶었던 노래를 만들어가는데…','15세관람가','0','/resources/images/subPoster/비긴어게인.jpg','/resources/images/movie_trailer/비긴 어게인 메인예고편.mp4','키이라 나이틀리, 마크 러팔로, 애덤 리바인',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (174,'잃어버린세계를찾아서2','Journey 2: The Mysterious Island','/resources/images/mainPoster/잃어버린세계를찾아서2.jpg','action','사라진 엄마를 찾아야 한다! 홈즈 가문답게 탐정 본능 장착하고 런던에 간 에놀라. 하지만 시작부터 도망자 신세의 귀족 청년과 엮여버렸다. 그 와중에 오빠 셜록까지 따돌려야 한다니. 미스터리 가득한 이 모험, 무사히 마칠 수 있을까?','전체관람가 ','0','/resources/images/subPoster/잃어버린세계를찾아서2.jpg','/resources/images/movie_trailer/잃어버린세계를찾아서2.mp4','드웨인 존슨, 마이클 케인, 조쉬 허처슨',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (178,'미션 임파서블','Mission: Impossible - Rogue Nation','/resources/images/mainPoster/미션임파서블.jpg','action','시리즈 사상 최악의 위기!
역대 가장 불가능한 미션이 시작된다!
미국정부로부터 해체 통보를 받게 된 최첨단 첩보기관 IMF(Impossible Mission Force). ‘에단 헌트(톰 크루즈)’를 포함한 팀원들은 모두 뿔뿔이 흩어지게 되고, 정체불명의 테러조직 ‘신디케이트’는 IMF 전멸 작전을 펼친다...','15세관람가 ','0','/resources/images/subPoster/미션임파서블.jpg','/resources/images/movie_trailer/미션임파서블.mp4','톰 크루즈, 제레미 레너, 사이먼 페그',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (169,'사운드 오브 뮤직','The Sound Of Music','/resources/images/mainPoster/사운드오브뮤직.jpg','music','음악을 사랑하는 말괄량이 견습 수녀 ‘마리아’는 원장 수녀의 권유로 해군 명문 집안 폰 트랩가의 가정교사가 된다. ‘마리아’는 좀처럼 마음의 문을 열지 않는 폰 트랩가의 일곱 아이들에게 노래를 가르치며 점차 교감하게 되고, 엄격한 ‘폰 트랩 대령’ 역시 마음의 문을 열게 된다. 그러던 어느 날, ‘마리아’는 자신이 ‘폰 트랩 대령’을 사랑하고 있다는 사실을 깨닫게 되고, 자신만의 비밀을 간직한 채 아이들의 곁을 떠나 다시 수녀원에 들어가기로 결심하는데…','전체관람가','0','/resources/images/subPoster/사운드오브뮤직.jpg','/resources/images/movie_trailer/사운드 오브 뮤직.mp4','줄리 앤드류스, 크리스토퍼 플러머, 엘레노 파커',to_date('20/10/08','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (173,'응답하라1994','Reply 1994','/resources/images/mainPoster/응답하라1994.jpg','drama','1994년을 배경으로, 지방 사람들의 눈물겨운 상경기와 농구대잔치, 서태지와 아이들 등의 사회적 이슈를 담은 드라마','15세관람가 ','0','/resources/images/subPoster/응답하라1994.jpg','/resources/images/movie_trailer/응답하라1994.mp4','성동일, 이일화, 고아라',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (133,'드래곤 길들이기','How To Train Your Dragon','/resources/images/mainPoster/드래곤길들이기.jpg','animation','바이킹 족장의 아들이지만 겁이 많은 히컵 호렌더스 해덕 3세가 전사로서의 패기를 입증하기 위해 용을 죽여야 하는 임무를 맡게 된다.','전체관람가','0','/resources/images/subPoster/드래곤길들이기.jpg','/resources/images/movie_trailer/드래곤 길들이기.mp4','제이 배루셸, 제라드 버틀러, 크레이그 퍼거슨',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (134,'해피 피트','Happy Feet!','/resources/images/mainPoster/해피 피트.jpg','animation','어린 펭귄 멈블은 친구들과 달리 짝꿍을 매료시킬 만큼 노래 실력이 좋지 못하지만, 최고의 탭댄스 실력을 갖고 있다.','전체관람가','0','/resources/images/subPoster/해피 피트.jpg','/resources/images/movie_trailer/해피 피트.mp4','일라이저 우드, 로빈 윌리엄스, 브리트니 머피',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (142,'하울의 움직이는 성','Howl`s Moving Castle','/resources/images/mainPoster/하울의 움직이는 성.jpg','animation','아버지가 물려준 모자 가게를 지키는 수수한 소녀 소피. 전쟁도, 미녀의 심장을 노리는 마법사의 소문도 먼 세상 이야기일 뿐. 하지만 마녀의 저주로 할머니가 되면서, 소피의 인생이 회전목마처럼 힘차게 움직이기 시작한다.','전체관람가','0','/resources/images/subPoster/하울의 움직이는 성.jpg','/resources/images/movie_trailer/하울의 움직이는 성.mp4','바이쇼 지에코, 기무라 타구야, 미와 아키히로',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (146,'미스 페레그린과 이상한 아이들의 집','Miss Peregrine`s Home for Peculiar Children','/resources/images/mainPoster/미스 페레그린과 이상한 아이들.jpg','fantasy','미스 페레그린을 찾아가라. 할아버지의 유언을 좇아 외딴 섬에 이른 소년. 그곳에서 별종이 모여 사는 집에 초대된다. 하늘로 떠오르고 식물을 조종하고 불을 만드는 아이들. 누구도 본 적 없는 세상이, 지금 눈앞에 펼쳐지고 있어!','12세관람가','0','/resources/images/subPoster/미스 페레그린과 이상한 아이들.jpg','/resources/images/movie_trailer/미스 페레그린과 이상한 아이들의 집.mp4','에바 그린, 에이사 버터필드, 새뮤얼 L.잭슨',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (148,'타이탄','Clash of the Titans','/resources/images/mainPoster/타이탄.jpg','fantasy','용맹한 페르세우스는 아름다운 공주 안드로메다의 목숨을 구하기 위해 강력한 적과 맞서 싸워야 한다.','12세관람가','0','/resources/images/subPoster/타이탄.jpg','/resources/images/movie_trailer/타이탄.mp4','샘 워딩턴, 리엄 니슨, 랄프 파인즈',to_date('20/10/07','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (175,'분노의질주','Fast & Furious Presents: Hobbs & Shaw','/resources/images/mainPoster/분노의질주.jpg','action','공식적으로만 세상을 4번 구한 전직 베테랑 경찰 ‘루크 홉스’(드웨인 존슨)
 분노 조절 실패로 쫓겨난 전직 특수요원 ‘데카드 쇼’(제이슨 스타뎀)
 99.9% 완벽히 다른 두 남자는 전 세계를 위협하는 불가능한 미션을 해결하기 위해
 어쩔 수 없이 한 팀이 되고 마는데…','12세관람가 ','0','/resources/images/subPoster/분노의질주.jpg','/resources/images/movie_trailer/분노의질주.mp4','드웨인 존슨, 제이슨 스타뎀, 이드리스 엘바',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (184,'공조','Confidential Assignment','/resources/images/mainPoster/공조.jpg','action','비밀리에 제작된 위조 지폐 동판을 탈취하려는 내부 조직에 의해
 작전 중 아내와 동료들을 잃게 된 특수 정예부대 출신의 북한형사 "림철령"(현빈).
  동판을 찾아야만 하는 북한은 남한으로 숨어든 조직의 리더 "차기성"(김주혁)을 잡기 위해
 역사상 최초의 남북 공조수사를 요청하고, 그 적임자로 철령을 서울에 파견한다...','15세관람가 ','0','/resources/images/subPoster/공조.jpg','/resources/images/movie_trailer/공조.mp4','현빈, 유해진, 김주혁',to_date('20/10/09','RR/MM/DD'));
Insert into MOVIE_MAIN (MOVIE_ID,MOVIE_TITLE,MOVIE_SUB_TITLE,MOVIE_POSTER_PATH,MOVIE_CATEGORY,MOVIE_CONTENT,MOVIE_RATING,MOVIE_LIKE,MOVIE_CARD_BACK_PATH,MOVIE_CARD_VIDEO_PATH,MOVIE_ACTOR,INPUTDATE) values (183,'히트맨','HITMAN: AGENT JUN','/resources/images/mainPoster/히트맨.jpg','action','웹툰 작가가 되고 싶어 국정원을 탈출한 비밀 프로젝트 방패연 출신 전설의 암살요원 "준". 그러나 현실은 연재하는 작품마다 역대급 악플만 받을 뿐이다...','15세관람가 ','0','/resources/images/subPoster/히트맨.jpg','/resources/images/movie_trailer/히트맨.mp4','권상우, 정준호, 황우슬혜',to_date('20/10/09','RR/MM/DD'));

update movie_main set movie_category = '액션' where movie_category = 'action';
update movie_main set movie_category = '로맨스' where movie_category = 'romance';
update movie_main set movie_category = '드라마' where movie_category = 'drama';r
update movie_main set movie_category = '코메디' where movie_category = 'comedy';
update movie_main set movie_category = '애니메이션' where movie_category = 'animation';
update movie_main set movie_category = '스릴러' where movie_category = 'thriller';
update movie_main set movie_category = '음악' where movie_category = 'music';
update movie_main set movie_category = '판타지' where movie_category = 'fantasy';


